version: '3.8'

services:
  ping-service:
    image: containerreg.schoors.duckdns.org/mqtt-power-service:latest
    container_name: mqtt-power-service
    restart: unless-stopped
    env_file: 
      - stack.env
    volumes:
      - ./logs:/app/logs
    networks:
      macvlan_net:
        ipv4_address: 192.168.50.202

networks:
  macvlan_net:
    external: true
    name: macvlan_network
